hw_7
eugene-okulik/ilya_slyadnev pull request #12
Opened 2023-12-04 23:09 UTC by Elieeeya

2023-12-05 07:38 UTC, eugene-okulik requested changes

2023-12-05 07:38 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_7/task_3.py
> +    print(number)
В задании было

> Главное отличие - выполните всё с использованием функций

Но функций нет ((

2023-12-05 21:37 UTC, Elieeeya commented on homework/ilya_slyadnev/Homework_7/task_3.py
> +    print(number)
забыл:)

2023-12-07 10:27 UTC, eugene-okulik approved these changes
Ну, чисто по определению да, но в таком виде эта функция бессмысленна. То же самое, что написать for вне функции. Функцию хорошо бы сделать для чего-то повторяющегося.  
Например, код
```python
number = int(string_result.split()[-1]) + 10
print(number)
```
поместить в функцию и дергать её в цикле.
И если, например, это сделать не циклом, то такая функция вообще musthave, если каждый результат обрабатывать отдельным кодом.

2023-12-07 10:30 UTC, merged