hw_11
eugene-okulik/ilya_slyadnev pull request #20
Opened 2023-12-18 21:05 UTC by Elieeeya

2023-12-19 15:15 UTC, eugene-okulik requested changes
В целом норм, но я специально притянул за уши эти material и has_text, чтобы намекнуть на общие для всех книг характеристики.  
Ну и обращение к родительскому классу лучше поправить. Видел, как такое делало код неподдерживаемым.

2023-12-19 15:15 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_11/task_1.py
> +        self.has_text = has_text
Если мы говорим о библиотеке, то вряд ли там будут небумажные книги без текста. Скорее всего, наличие текста и материал для всех книг будет одинаковым. А поэтому это можно добавлять не в индивидуальныые характеристики объекта, а в свойства класса.

2023-12-19 15:15 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_11/task_1.py
> +        Book.__init__(self, material, has_text, title, author, num_pages, ISBN, reserved)
Если завтра родительским классом для этого класса станет не класс Book, то это всё поломается, т.к. можно взять и забыть поменять это здесь. Обращение к родительскому классу делается через `super()`

2023-12-19 15:15 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_11/task_1.py
> +        print("\n")  # это я для себя, так легче воспринимать
Ты хотел здесь именно две строки сделать в качестве разделителя? Если да, то ок, но, подозреваю, что тебе хватило бы и одной. Для одной строки можно сделать пустой принт `print()` - он в любом случае после себя пустую строку добавляет. А в твоем случае он добавляет пустую строку после пустой строки. Если ты так и хотел, то ок. Но, может я чо полезного сейчас рассказал ))

2023-12-20 14:00 UTC, Elieeeya commented
Поправил :)

2023-12-21 08:06 UTC, eugene-okulik approved these changes

2023-12-21 08:06 UTC, merged