hw_13
eugene-okulik/ilya_slyadnev pull request #24
Opened 2023-12-30 13:54 UTC by Elieeeya

Не совсем уверен, что правильно понял условия задачки.
Если все таки выполнил не корректно, просьба описать условия более детально, а именно что требуется сделать :)
Спасибо!

2023-12-30 15:16 UTC, eugene-okulik requested changes
Из критичного, нужно поправить построение пути к файлу, чтобы эту программу можно было запустить из любого места компа и с любого компа, на котором есть этот репозиторий.

2023-12-30 15:16 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_13/task_1.py
> +file_path = "../../eugene_okulik/hw_13/data.txt"
Обращение по захардкоженному пути очень сильно ограничивает возможность запуска этой программы. Твоя программа на винде имеет все шансы не запуститься, как ни запускай.  
В занятии я показывал что делать, чтобы путь получался универсальным.

2023-12-30 15:16 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_13/task_1.py
> +    match = re.match(r"(\d+)\. (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d+)\s+-\s+(.*)", line)
Регулярки это круто. Особенно когда мы говорим не о питоне. Питон - это про простоту. Я могу понять что делается в этой строке только благодаря тому, что я знаю в чем состоит задание.  
В задании было написано, что программа находит в каждой строке дату. т.е. номер и текст искать не нужно. И так как дата всегда находится в каждой строке на одном и том же месте, ее можно было искать опираясь на позицию: или с помощью `split()` или с помощью `index()`  
Твое решение тоже хорошее, можешь не исправлять. Но просто имей в виду, что в питоне нужно мудрить только тогда, когда по-другому никак.

2023-12-30 15:16 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_13/task_1.py
> +    if "распечатать эту дату" in action and "на неделю позже" in action:
Ну, в целом, такое понимание и выполнение тоже сойдет, но если бы нужно было так, то в тексте было бы написано, что программа должна распознать какое действие написано после даты и выполнить его. Но такое задание было бы, если бы мы учились на курсе искусственного интеллекта ))  
Можно было просто так:
```python
if number.starts_with('1'):
```
ну и в функцию передавать не action, а number, который ты там регуляркой или с помощью enumerate нашел.

2023-12-30 15:18 UTC, eugene-okulik commented
> Не совсем уверен, что правильно понял условия задачки. Если все таки выполнил не корректно, просьба описать условия более детально, а именно что требуется сделать :) Спасибо!

Ты это, если что-то не до конца понятно по заданию, ты спрашивай.

2024-01-01 15:44 UTC, Elieeeya commented
Понял! Поправил домашку 
Спасибо за разъяснения :)

2024-01-02 08:37 UTC, eugene-okulik approved these changes

2024-01-02 08:37 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_13/task_1.py
> +current_dir = os.path.dirname(os.path.abspath(__file__))
А для чего `os.path.abspath`, если можно было `os.path.dirname(__file__)`?

2024-01-02 08:37 UTC, eugene-okulik commented on homework/ilya_slyadnev/Homework_13/task_1.py
> +        process_date_action(date_str, number)
У тебя есть переменная `line_number`, которая нигде не используется. Если таких переменных не избежать, их называют так: `_`, но это не твой случай - ее можно было не создавать.

2024-01-02 08:38 UTC, merged