add hw_21
eugene-okulik/ilya_slyadnev pull request #39
Opened 2024-02-21 14:06 UTC by Elieeeya

2024-02-22 08:03 UTC, eugene-okulik requested changes

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/tests/test_api.py
> +    object_id = test_create_object(objects_api, data)
Шаг по созданию объекта в этом тесте не является шагом теста, а является предусловием. Предусловия в pytest оформляются через фикстуры.

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/tests/test_api.py
> +                    message="Name of the object is not updated as expected")
Проверки, касающиеся какого-то эндпоинта лучше выносить в методы класса, как я показывал в видео. В текущем виде они очень затрудняют читаемость теста.

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/endpoints/endpoints.py
> +        return self.api.send_request("DELETE", f"objects/{object_id}")
Отдельные эндпоинты очень удобно разносить на разные классы, чтобы в классе конкретного эндпоинта можно было реализовывать те методы и свойства, которые касаются непосредственно этого эндпоинта.

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/tests/test_api.py
> +
Во всех тестах отсутствует проверка код ответа сервера, а это является базовой проверкой при тестировании API

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/tests/test_api.py
> +                    message="Object was not deleted successfully")
Проверка, что сервер правильно ответил на запрос на удаление недостаточно проверяет функцию удаления. Для хорошего теста нужно убедиться, что удаляемый объект действительно удалён.

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/tests/test_api.py
> +    }
Так как в твоем проекте предусмотрено место, в котором хранятся данные, хорошо бы все данные вынести из тестов и хранить их отдельно.

2024-02-22 08:03 UTC, eugene-okulik commented on test_api_slyadnev/tests/test_api.py
> +    Assertion.equal(response_data.get("data"), data["data"], message="Data of the object is not as expected")
В тестах нужно стараться по максимуму избавляться от питоновского и делать так, чтобы все обращения были только к тем свойствам и методам, которые ты сам создал.   
Так, код
```python
new_object.check_the_name_is_the_same_as_sent()
```
выглядит более читаемо чем
```python
Assertion.equal(response_data.get("name"), data["name"], message="Name of the object is not as expected")
```
А сам код, который эту проверку осуществляет будет спрятан в методах твоего фреймворка.

2024-02-24 23:20 UTC, ik-slyadnev commented
хз, Евгений, Яндекс Практикум и QA GURU учат другим подходам ... )
вроде Питон это простота, а все что ты описал это сложности )

2024-02-25 12:17 UTC, eugene-okulik commented
> хз, Евгений, Яндекс Практикум и QA GURU учат другим подходам ... ) вроде Питон это простота, а все что ты описал это сложности )

1. Когда ты выполняешь задание на другом курсе, ты выполняешь так, как там учат. Потому что ты практикуешь то, чему тебя там научили.  
2. Если ты изучаешь что-то на разных курсах и на разных курсах разные подходы, то это огромный бонус тебе - ты после этого сможешь выбрать тот подход, который тебе больше нравится, ведь ты со всеми из них познакомился и попрактиковал.
3. Простота питона в том и состоит, что он простой и то, что мы делаем, должно быть просто использовать, читать, поддерживать. Та структура, которая использована у тебя, вносит очень много путаницы и внесение изменений потребует больше усилий, чем если структурировать всё получше. И в этом ничего сложного - простой ООП. Кстати, у тебя в структуре и классы можно было не создавать. Классы нам нужны тогда, когда мы готовы воспользоваться инкапсуляцией, наследованием и полиморфизмом. У тебя ничего из этого не используется - можно было просто создать модули с необходимыми функциями. А так - ты просто усложняешь простой питон, не извлекая из этого усложнения никакой пользы.
4. Яндекс Практикум и QA GURU не являются эталоном. Не знаю как на эти курсах, но многие курсы дают другие структуры, так как они недостаточно хорошо дают знания по ООП - и в итоге студенты не могу справиться с построением хорошей структуры тестов через классы.

2024-04-02 12:30 UTC, closed without merging